name: CI/CD workflow

on:
  pull_request:
    branches:
      - develop
      - main
  push:
    branches:
      - develop
      - main

permissions:
  id-token: write
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ github.event.pull_request.base.ref || github.ref_name }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.29

      - name: Environment
        run: |
          touch .env
          echo "NODE_ENV=${{ vars.NODE_ENV }}" >> .env
          echo "SERVER_HOST=${{ vars.HOST }}" >> .env
          echo "SERVER_PORT=${{ vars.PORT }}" >> .env
          echo "JWT_SECRET=${{ vars.JWT_SECRET }}" >> .env
          echo "MONGODB_URI=${{ vars.MONGODB_URI }}" >> .env
          echo "AWS_SES_REGION=${{ vars.AWS_REGION }}" >> .env
          echo "AWS_SES_ID=${{ secrets.AWS_SES_ID }}" >> .env
          echo "AWS_SES_SECRET=${{ secrets.AWS_SES_SECRET }}" >> .env
          echo "AWS_SES_SOURCE=${{ vars.APAWS_SES_SOURCEP_URL }}" >> .env
          echo "APP_URL=${{ vars.APP_URL }}" >> .env
          echo "" >> .env

      - name: Install
        run: bun i

      - name: Format
        run: bun run format

      - name: Lint
        run: bun run lint

      - name: Test
        run: bun run test

      - name: Build
        run: bun run build
