name: Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_ENV: test
  MONGODB_HOST: localhost
  MONGODB_PORT: 27017
  HOST: 0.0.0.0
  PORT: 4000

jobs:
  test:
    runs-on: ubuntu-latest
    environment: ${{ github.event_name == 'push' && 'production' || 'test' }}

    services:
      mongodb:
        image: mongo:7.0.5-jammy
        ports:
          - 27017:27017
          options: >-
            --health-cmd "mongosh --eval 'db.hello()'"
            --health-interval 3s
            --health-timeout 2s
            --health-retries 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.29

      - name: Set up environment variables
        run: |
          touch .env
          echo "NODE_ENV=${{ env.NODE_ENV }}" >> .env
          echo "SERVER_HOST=${{ env.HOST }}" >> .env
          echo "SERVER_PORT=${{ env.PORT }}" >> .env
          echo "JWT_SECRET=${{ vars.JWT_SECRET }}" >> .env
          echo "BREVO_API_KEY=${{ secrets.BREVO_API_KEY }}" >> .env
          echo "BREVO_FROM_EMAIL=${{ vars.BREVO_FROM_EMAIL }}" >> .env
          echo "BREVO_FROM_NAME=${{ vars.BREVO_FROM_NAME }}" >> .env
          echo "SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}" >> .env
          echo "MONGODB_URI=mongodb://${{ env.MONGODB_HOST }}:${{ env.MONGODB_PORT }}" >> .env
          echo "APP_URL=${{ vars.APP_URL }}" >> .env

      - name: Install dependencies
        run: bun i

      - name: Test
        run: bun run test
